// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxktosxshxjrwyswymhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4a3Rvc3hzaHhqcnd5c3d5bWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODkzMTIsImV4cCI6MjA2ODM2NTMxMn0.zooBJtBOYEYsgeXfho2SjAku5DEFMKaspTFP_YxWAIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});